#!/usr/bin/env node
// Render a gps trace as a colored path over its map, without editing the map.
// Writes next to the trace:  <slug>.d2 (imports the map, restyles hop nodes, adds missing nodes + path edges)
//                            <slug>.svg (clickable)
// and rewrites index.md in the traces dir, plus a pointer comment in the map header.
// Usage: node render-path.mjs pkg/architecture.gps/<slug>.json  (map: pkg/architecture.gps/map.d2)
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile, MAP_NAME, mapNodes } from "./lib.mjs";

const PATH_COLOR = "#2f9e44";
const PATH_FILL = "#ebfbee";

const tracePath = resolve(process.argv[2] ?? "");
if (!process.argv[2] || !existsSync(tracePath)) {
	console.error("usage: render-path.mjs pkg/architecture.gps/<slug>.json");
	process.exit(2);
}
const dir = dirname(tracePath);
const slug = basename(tracePath, ".json");
if (slug === MAP_NAME) {
	console.error(`slug "${MAP_NAME}" is reserved for the map (${MAP_NAME}.d2/${MAP_NAME}.svg); rename the trace`);
	process.exit(2);
}
const trace = JSON.parse(readFileSync(tracePath, "utf8"));
const mapPath = resolve(dir, trace.map);
if (!existsSync(mapPath)) throw new Error(`map not found: ${mapPath}`);

// Quote for a d2 double-quoted label. `$` must be escaped or d2 treats it as a variable.
const q = (s) => `"${String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$").replace(/\n/g, "\\n")}"`;
const link = (hop) => q(`vscode://file${join(trace.root, hop.file)}:${hop.line}`);

// Validate node / container keys against the compiled map, otherwise d2 silently creates new empty nodes.
const keys = new Set(mapNodes(mapPath).map((n) => n.key));
const errors = [];
for (const hop of trace.hops) {
	if (hop.node && !keys.has(hop.node)) errors.push(`step ${hop.step}: node "${hop.node}" not in map`);
	if (!hop.node && hop.container && !keys.has(hop.container)) errors.push(`step ${hop.step}: container "${hop.container}" not in map`);
	if (!hop.node && !hop.label) errors.push(`step ${hop.step}: new node needs a label`);
}
if (errors.length) {
	console.error(errors.join("\n"));
	process.exit(1);
}

const keyOf = (hop) => hop.node ?? `${hop.container ? `${hop.container}.` : ""}gps${hop.step}`;
const first = trace.hops[0];
const last = trace.hops.at(-1);
const out = [
	`# gps path: ${trace.query.from} -> ${trace.query.to}`,
	`# intent: ${trace.query.intent}`,
	`# Generated by render-path.mjs from ${slug}.json (commit ${trace.commit ?? "?"}). Edit the JSON, not this file.`,
	`# Green numbered edges (P1-P${trace.hops.length - 1}) are the traced path; other edges are dimmed.`,
	"",
	`...@${relative(dir, mapPath)}`,
	"",
	"classes: {",
	`  gpspath: {style: {stroke: "${PATH_COLOR}"; stroke-width: 5; font-color: "${PATH_COLOR}"; bold: true}}`,
	"}",
	// Dim every map edge. The glob also hits path edges, so they override opacity explicitly (a class cannot).
	"(** -> **)[*].style.opacity: 0.2",
	"",
	`gps_legend: ${q(`PATH  A -> B\n\nA: ${trace.query.from}\nB: ${trace.query.to}\n\n${trace.query.intent}${trace.gaps?.length ? `\n\ngaps:\n- ${trace.gaps.join("\n- ")}` : ""}`)} {`,
	"  near: top-left",
	`  style: {stroke: "${PATH_COLOR}"; stroke-width: 3; fill: "${PATH_FILL}"; font-color: "${PATH_COLOR}"}`,
	"}",
	"",
];

for (const hop of trace.hops) {
	const marker = hop === first ? "A. " : hop === last ? "B. " : "";
	const nodeStyle = `{stroke: "${PATH_COLOR}"; stroke-width: ${marker ? 6 : 4}; fill: "${PATH_FILL}"${marker ? "; double-border: true" : ""}}`;
	if (hop.node) {
		out.push(`${hop.node}.style: ${nodeStyle}`);
	} else {
		out.push(`${keyOf(hop)}: ${q(`${marker}${hop.label}`)} {`, `  link: ${link(hop)}`, `  style: ${nodeStyle}`, "}");
	}
}
out.push("");

let edgeNum = 0;
for (let i = 0; i < trace.hops.length - 1; i++) {
	const a = trace.hops[i];
	const b = trace.hops[i + 1];
	if (keyOf(a) === keyOf(b)) continue;
	edgeNum++;
	out.push(`${keyOf(a)} -> ${keyOf(b)}: ${q(`P${edgeNum}. ${a.edge ?? a.carries ?? ""}`)} {class: gpspath; style.opacity: 1}`);
}

const d2Path = join(dir, `${slug}.d2`);
const svgPath = join(dir, `${slug}.svg`);
writeFileSync(d2Path, `${out.join("\n")}\n`);
compile(d2Path, svgPath);
console.log(`wrote ${relative(process.cwd(), d2Path)}\nwrote ${relative(process.cwd(), svgPath)}`);

const checkLinks = join(dirname(fileURLToPath(import.meta.url)), "check-links.mjs");
try {
	const res = execFileSync("node", [checkLinks, svgPath], { encoding: "utf8" });
	console.log(res.trim().split("\n").at(-1));
} catch (e) {
	console.log(e.stdout);
	process.exitCode = 1;
}

// index.md: one small file future agents read instead of every trace.
const rows = readdirSync(dir)
	.filter((f) => f.endsWith(".json"))
	.sort()
	.map((f) => {
		const t = JSON.parse(readFileSync(join(dir, f), "utf8"));
		const cell = (s) => String(s ?? "").replace(/\|/g, "/").replace(/\n/g, " ");
		return `| [${f}](${f}) | \`${cell(t.query.from)}\` | \`${cell(t.query.to)}\` | ${cell(t.query.intent)} | ${t.hops.length} | ${cell(t.commit)} |`;
	});
writeFileSync(
	join(dir, "index.md"),
	[
		`# gps paths over ${basename(mapPath)}`,
		"",
		"Verified A -> B traces. Before tracing, look for a matching from/to here and run",
		"`verify-trace.mjs <json>` (gps skill scripts). VERIFIED or DRIFTED (fix with --fix) means reuse it: no re-trace.",
		"Each JSON has a `summary` that answers the question; each `<slug>.svg` draws the path over the map.",
		"",
		"| trace | from (A) | to (B) | intent | hops | commit |",
		"|---|---|---|---|---|---|",
		...rows,
		"",
	].join("\n"),
);

// Pointer in the map header so agents reading the map find saved paths.
const pointer = `# Saved A -> B paths: ${join(relative(dirname(mapPath), dir), "index.md")} (reuse before re-tracing).`;
const mapText = readFileSync(mapPath, "utf8");
if (!mapText.includes(pointer)) {
	const lines = mapText.split("\n");
	const at = lines.findIndex((l) => !l.startsWith("#"));
	lines.splice(at < 0 ? 0 : at, 0, pointer);
	writeFileSync(mapPath, lines.join("\n"));
	console.log(`added path pointer to ${relative(process.cwd(), mapPath)}`);
}
